sudo: true
dist: trusty
language: php

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/.composer/cache/files
    - node_modules

addons:
  sonarcloud:
    organization: "wirecard"
  browserstack:
    username:
      secure: "vBaR5gsVuNjMgDn06glSMHfVhN7zhh7hePPgRUgMD2E2et1MLCyqBGPO21oUPUjWrVImSXYayypue0dsFi+OZOdolgP2HOFfogmRs7OFfcSAfq9WYR9i6iDv9NcLCH6zk76a2ckQToBQJjwpj25Bxhbnu7wXgGsKCYrXqfcz7AWO/GduWEdRWbLxMrT8qfvMNFT+W9TPVywb6ZWkMeLWOOkNS9JoMXrXCRw77i4AQeFnaIfmC/PX460iTnpxHecGIW/oHtKACOf898P50bYxtvt7Rf98rsOnq4FFS5rkUxL0KFoI1PFBnf/AgZKBEhC2MzblcJZ2gaiuHIcKGKVgUZ75LJjeYEKPZ4I28naJH5U8MhTqyyehAJtXJEUzSBq9gQGKx8HuAvKpiCR/jWCM4E0VsNkRbUuFxyPlvicbSvk4mPcljSpJPaIfQqzyIvVoKBg+lWNH45DqQd/FxmkREGWASQoI61715+9qvpnlvIBGJ0jX6BIQ87cmwjNZnfhP22txRLREOT/y+WdjV5ZGDQNvhAH7aseQNMSLWQXAntj8zyFnHomy4rS4/THJVwdMV7UWtV3m+fms4CzdhgTLBC4ps6Q2w2jI50ZBdj42bFDjCuJyg13USo3xbpYsZvrrxuNIkjCCDWNJEOzVL2dNlQAoxCtauVC1wvmCGALjB9c="
    access_key:
      secure: "gbQxLw3xmkieBuvsQNIzMArfSZke0sjmp9R4ROMFBEom0WJRri2iPzAV5q943L9Ohr39QtyX2lOcgiBCS0Ye0TBXRq8FwvVPeuXuyv5bzJogsXW3NzlJcWvmFInGLlfOZ5duNvTOrKiqSIjo+3kK/14o5C5UcEr6VRCkP0ljw6LHmQf8D7WH+wBxiei+Vi5EAU885mL9hUfzbqBLhDBxX3y40OTCBbPu+V/+1iPyHc7RLX/4Sv6XT2shEtGV1XhBx8HxJa2mzB92xSwkV5OuRrzvJwnt5JNzEqpxUeF0TcEblPwIKnYEoeZoutZfBXkuB+i7WcsX9PCqRFVbJDqzgvV/QEuLh4UX91kUuTVZ+RnTpIzWYXGpWJYn+dbs8PFgXGTjlj+xG4gpfSPZcHNgSKJxZp/XlTWlVKUGC7p5FORHjhbgAyIIqw+Ks6hrT2tvbua9OSBZ+zaN+UBPmcgJHaJE++FTuzbbVDRzR6KTRWqys/3lgo5ePpycFv0CUc5KJAN2Yh4bWxqTORAXyyUJoQ1sc0VNQlfSq8/N1mhecLBWS23NiAFoRYz+GTpyq39uzLuMUGTEo4U821079j+3FnKt7GefWxm/qx2XR5R+aTK5SLFMH+XiJaDz3bIij1w9Rh7ebIO7C8HLACG7/0iWQsq/fGhSlQgZl0wyG2SEv0Y="

php:
  - 7.1
  - 7.0
  - 5.6

services:
  - mysql

env:
  global:
    - secure: ${SONAR_TOKEN}
    - COMPOSER_ARGS="--no-interaction"
    - PLUGIN_NAME=WirecardShopwareElasticEngine
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - github_token:
        secure: "gH+IJRS0uQe2G/gg4nL0UgQxh4Tog16vQIBzWgQiFUjmQM/jMvUtw6kW4ixcusOPGR4rqKuLFCd8gbDg/I848VNDb7a+xg+wGm7KvognnbcxbnB0TcxNcPTGZUWXbSqGi3z8YhAaaa1LfrROM3qS4LeU3Bz+B7ZpdbA7xqzkmBRPgEdsv7OLmCwow2e6jreeGcCAqM34q84JavZkWcoHCQbLoknwyNCzilMKUN8fe+Ih46o1O0iuVOv9lAWIOLlAJJNcrX+kamv4RhrtDQwyVWsnDB2OO2Me4Lr4Bkqy9pN+diszgX8OzhOnkFl+ZXYTIUI5NxK3kAkd4lKOO3QgHIoveSmeoaS/mrC5kflNs6vN399Jm8X4gSmxUhkl01hEAfEqL+BiW2o22/Pq8WeMVVaQy3ONUwlSGGBkk/IkckbG/LzpJv5Jjztfi8Xfl9JF1jO/0BABsqodx/pEbDzIKKb3S/U/EHmCXV8zqmD67E/PIii3Y9kxeVaDNdWT5u4O69Pt9sR7csA8OL8YS8th/d825v4BTPswIFxn1vXB1sTKJZGwyO+fu53CE7qcZEMc/+NJnfLZBhIbV9SE1zVRsDPX1AiruPd/sXjYy01AR4SYdCO+RrdyVWoIE65hV/MOGgvu327jI13ZIpFE2PwE1fPj6JqTtrW5YugLCOQUGd0="

install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis_retry composer install $COMPOSER_ARGS
  - travis_retry npm install
  - npm list --depth=0
  - composer show

before_script:
  # install apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%DOCUMENT_ROOT%?${SHOPWARE_DIRECTORY}?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

  # install shopware
  - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch 5.4
  - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - cp ${TRAVIS_BUILD_DIR}/build/travis-shopware-config.php ${SHOPWARE_DIRECTORY}/config.php
  - mv ${TRAVIS_BUILD_DIR} ${SHOPWARE_DIRECTORY}/custom/plugins/${PLUGIN_NAME}
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:plugin:refresh
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:plugin:install ${PLUGIN_NAME}
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:plugin:activate ${PLUGIN_NAME}
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:cache:clear
  - rm -rf ${SHOPWARE_DIRECTORY}/var/cache
  - cd ${SHOPWARE_DIRECTORY}/custom/plugins/${PLUGIN_NAME}

script:
  - composer cs-check
  - npm run lint
  - php ${SHOPWARE_DIRECTORY}/bin/console wirecardelasticengine:payment:activate
  - npm run test:runner
  - composer test-coverage
  - sonar-scanner

after_script:
  - travis_retry composer upload-coverage

after_failure:
  - sudo cat /var/log/apache2/error.log
  - cat ${SHOPWARE_DIRECTORY}/composer.lock
  - cat ${SHOPWARE_DIRECTORY}/var/log/*.log
